### PR TITLE
Performance buster and LED to all controllers

### PR DESCRIPTION
**Pull request by ImpeezaW**
Change on `ftp.c`
Change `#define SOCK_BUFFERSIZE 0x4000` to `#define SOCK_BUFFERSIZE 0x10000` in order to enhance performance

Change on `led.c`
Enable the information via LED on all pads.

### CODE REVIEW

**Comment by cathery** [comment]
Thank you for the PR! Have you tried out the changes locally? I tried running the build on 18.1.0|AMS 1.8.0 and I kept getting errors when i tried to do anything through my FileZilla client. It seems too unstable to merge in the current state

**Comment by impeeza** [comment]
You are right, I am on FW 19.0.1, ATM 1.8.0, I just made this tests:

A) The binaries downloaded from release page
B) A set of binaries made with latest commit on my local MSYS setup
C) Binaries made locally with only FTP.C changed
D) Binaries made locally with only LED.C changed
E) Binaries made locally with both FTP.C & LED.C changed

I uses Total Commander as FTP client.

Sadly all of them trend to eventually crash, and client get the error «can't open data connection»

This is my latest client log:


```
221 disconnecting
----------
Connect to: (11/08/2024 13:25:27)
hostname=192.168.100.17:5000
username=Impeeza
startdir=
192.168.100.17=192.168.100.17
220 Hello!
USER Impeeza
331 Password required
PASS ***********
230 OK
SYST
215 UNIX Type: L8
FEAT
211-
 MDTM
 MLST Type*;Size*;Modify*;Perm*;UNIX.mode;
 PASV
 SIZE
 TVFS
 UTF8
211 End
HELP SITE
214-The following commands are recognized
 ABOR ALLO APPE CDUP CWD DELE FEAT HELP LIST MDTM MKD MLSD MLST MODE
 NLST NOOP OPTS PASS PASV PORT PWD QUIT REST RETR RMD RNFR RNTO STAT
 STOR STOU STRU SYST TYPE USER XCUP XCWD XMKD XPWD XRMD
214 End
OPTS MLST Type;Size;Modify;Perm;UNIX.mode;
200 MLST OPTS Type;Size;Modify;Perm;UNIX.mode;
OPTS UTF8 ON
200 OK
Connect ok!
PWD
257 "/"
Get directory
TYPE A
200 OK
PORT 192,168,100,8,197,133
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CWD emuiibo
200 OK
PWD
257 "/emuiibo"
Get directory
PORT 192,168,100,8,197,135
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CWD overlay
200 OK
PWD
257 "/emuiibo/overlay"
Get directory
PORT 192,168,100,8,197,136
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CWD lang
200 OK
PWD
257 "/emuiibo/overlay/lang"
Get directory
PORT 192,168,100,8,197,138
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
TYPE I
200 OK
PORT 192,168,100,8,197,139
200 OK
RETR en.json
150 Ready
Download
Waiting for server...
226 OK
Copied (11/08/2024 13:25:40): ftp://192.168.100.17:5000/emuiibo/overlay/lang/en.json -> C:\Users\Impeeza\AppData\Local\Temp\_tc\en.json 3,840 bytes, 79 kbytes/s
CDUP
200 OK
PWD
257 "/emuiibo/overlay"
Get directory
TYPE A
200 OK
PORT 192,168,100,8,197,140
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CDUP
200 OK
PWD
257 "/emuiibo"
Get directory
PORT 192,168,100,8,197,142
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CDUP
200 OK
PWD
257 "/"
Get directory
PORT 192,168,100,8,197,143
200 OK
MLSD
150 Ready
Download
Waiting for server...
226 OK
CDUP
200 OK
PWD
257 "/"
Get directory
PORT 192,168,100,8,197,144
200 OK
MLSD
425 can't open data connection
PORT 192,168,100,8,197,145
200 OK
LIST
425 can't open data connection
Get directory
PORT 192,168,100,8,197,148
200 OK
LIST
425 can't open data connection
```

I am going to downgrade to FW 18.1.0 and repeat the tests.

**Comment by impeeza** [comment]
Just repeated the test after downgrading to FW 18.1.0, still ATM 1.8.0 and FileZilla 3.68.1 and the sysmodule eventually crashes:

image


The good thing about FileZilla is it retry 20 seconds after the fail so the connection can be reestablized some times.

Note> this test was made with the binaries from release page.

**Comment by impeeza** [comment]
Note2:  I am using Passive and non passive connections.

**Comment by cathery** [comment]
If you can manage to fix the errors I'll be happy to merge it. But keep in mind that the sysmodule shouldn't use too much memory, otherwise the user won't be able to run several sysmodules at the same time, and the system will crash. So some sacrifice in performance has to be made.
For full FTP performance I would recommend using mtheall's ftpd applet instead: https://github.com/mtheall/ftpd

**Comment by impeeza** [comment]
One latest test:

I took the code of commit e969376 and added the bare minimum changes to be able to load on FW 18.1.0 BUT ATM 1.8.0:

sys-ftpd.json added:
```
				"force_debug_prod":	false
```

MAIN.C, removed:
```
        .bsdsockets_version = 1,

```

UTIL.C, changed line to:
```
    rc = threadCreate(&pauseThread, inputPoller, NULL, NULL, 0x1000, 0x3B, -2);
```


built that code with latest devkitpro AND SADLY, THOSE BINARIES ALSO CRASH AFTER LISTING 3 FOLDERS WITH 200 files.

Something odd is happening with latest LibNX and DevKitPro.

**Comment by impeeza** [comment]
> If you can manage to fix the errors I'll be happy to merge it. But keep in mind that the sysmodule shouldn't use too much memory, otherwise the user won't be able to run several sysmodules at the same time, and the system will crash. So some sacrifice in performance has to be made. For full FTP performance I would recommend using mtheall's ftpd applet instead: https://github.com/mtheall/ftpd

Sadly your binaries on the release are suffering of the crash too, i have not the knowledge to debug the actual code on newest Atmosphère.

**Comment by impeeza** [comment]
@cathery has you been able to reproduce my crash on the latest binaries on the release page?

**Comment by ImpeezaW** [comment]
I think we will need to address the crashing of the latest release before add any code change.  regards @cathery

**Comment by ITotalJustice** [comment]
@impeeza when you experienced this crash, did the switch fatal? Or does ftpd stop responding all together?

If it's the latter, then it's likely that bsd socket ran out of memory. I experienced this a lot in ftpsrv when using extremely small socket buffers (16k fixed size).

The fix was to just give it more memory lol.

I can help with fixing this if needed

**Comment by impeeza** [comment]
Hello There,  My console keeps working fine, If I am running a game the game is not disturbed.

seems only the sysmodule crashes but recover after some time by it self.

**Comment by impeeza** [comment]
> @impeeza when you experienced this crash, did the switch fatal? Or does ftpd stop responding all together?
> 
> If it's the latter, then it's likely that bsd socket ran out of memory. I experienced this a lot in ftpsrv when using extremely small socket buffers (16k fixed size).
> 
> The fix was to just give it more memory lol.
> 
> I can help with fixing this if needed

Yes any help will be appreciated

**Comment by ELY3M** [comment]
I am having "can't open data connection" issues..... on only one switch.   I am on 19.0.1 FW and 1.8.0 AMS   I cant download the screenshots and it kept "crashing"        
I am trying to figure out why.

**Pull request closed without merging**
